FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# O '--host' permite que você acesse o Vite de fora do container
CMD ["npm", "run", "dev", "--", "--host"]