services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: alpes_backend_dev
    ports:
      - "3000:3000"  # exponha a porta do seu Node aqui
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      # AQUI: Adicionado o IP da sua rede para liberar o CORS
      - CORS_ORIGINS=http://localhost:5173,http://192-168-132-88.nip.io:5173
    networks:
      - alpes-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: alpes_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      # AQUI: Alterado para o IP da rede, assim qualquer máquina acha a API
      - VITE_API_URL=http://192-168-132-88.nip.io:3000
      - VITE_LEGACY_API_URL=http://192-168-132-88.nip.io:3000
    networks:
      - alpes-network
    depends_on:
      - server

networks:
  alpes-network:
    driver: bridge
