FROM node:22-alpine

WORKDIR /app

# Copia os arquivos de definição de pacotes
COPY package*.json ./

# Instala as dependências de desenvolvimento e produção
RUN npm install

# Copia o restante do código fonte
COPY . .

EXPOSE 3000

# Comando para iniciar o servidor em modo de desenvolvimento
CMD ["npm", "run", "dev"]